version: 0.2
env:
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - git config --global user.email "infbot-ifx@washpost.com"
      - git config --global user.name "Infbot IFX"
      - wget https://github.com/github/codeql-action/releases/latest/download/codeql-bundle-linux64.tar.gz
      - tar -xvzf ./codeql-bundle-linux64.tar.gz
      - rm codeql-bundle-linux64.tar.gz
  pre_build:
    commands:
      - echo "Getting the authentication token"
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain $codeArtifactDomain --domain-owner 026770442138 --query authorizationToken --output text`
  build:
    commands:
      - echo "Triggering build"
      - git checkout master
      - |
        if [ -n "$versionNumber" ] ; then
          if [[ $versionNumber =~ ^[0-9]+(\.[0-9]+){2}(\-[0-9a-zA-Z]+)?$ ]]; then
            echo "Increase the version to $versionNumber"
            ./mvnw build-helper:parse-version versions:set -DgenerateBackupPoms=false -DnewVersion=$versionNumber
          else
            echo "The versionNumber format provided doesn't meet the requirement"
            exit 1
          fi
        elif [ "$increaseMinor" = true ] ; then
          echo "Increase the minor version"
          ./mvnw build-helper:parse-version versions:set -DgenerateBackupPoms=false -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.nextMinorVersion}.0
        else
          echo "Increase the build number"
          ./mvnw build-helper:parse-version versions:set -DgenerateBackupPoms=false -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.incrementalVersion}-\${parsedVersion.nextBuildNumber}
        fi
      - ./mvnw -s .mvn/wrapper/settings.xml clean install deploy
      - export gitTagVersionNumber=$(mvn -q -s $CODEBUILD_SRC_DIR/.mvn/wrapper/settings.xml -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      - |
        if [ -n "$versionNumber" ] || [ "$increaseMinor" = true ] ; then
          echo "Upload runtime SDK Javadoc"
          export s3Uri=s3://arc-learning-center-static/docs/javadoc/ifx/sdk
          aws s3 cp target/apidocs "$s3Uri/latest/" --recursive --acl public-read
          aws s3 cp target/apidocs "$s3Uri/$gitTagVersionNumber/" --recursive --acl public-read
        fi
      - git add .
      - git commit -a -m "Commited on version ${gitTagVersionNumber}"
      - git push --set-upstream origin master
      - git tag ${gitTagVersionNumber}
      - git push origin --tags
      - mkdir codeql/output
      - codeql/codeql database create --language=java codeql/output/java-database
      - codeql/codeql database analyze codeql/output/java-database codeql/java-queries:codeql-suites/java-security-and-quality.qls --format=sarif-latest --sarif-category=java --output=codeql/output/java-results.sarif --download
      - codeql/codeql github upload-results --repository=WPMedia/arcxp-ifx-java-sdk --ref refs/tags/${gitTagVersionNumber} --sarif codeql/output/java-results.sarif