template: v1/cfn/ifx-team/codebuild-job.template.yaml
stack_name: codebuild-arc-platform-SDK-artifact
context:
  buildjob:
    name: arc_platform_sdk_build_prod
    action:
      type: BUILD_GENERAL1_SMALL
      image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      env_vars:
        codeArtifactDomain: com-arcpublishing-platform-prod
        increaseMinor: false
        versionNumber: "\"\""
      ssm_vars:
        GITHUB_TOKEN: /bootstrap/secrets/github-token
      buildspec: codebuild/buildspec-build.yml
      sourceLocation: https://github.com/WPMedia/arcxp-ifx-java-sdk.git
      timeout: 10
      branchName: master
